package me.robbie.boot.test.model;

import java.util.Date;

public class CourseDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.score
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.name
     *
     * @return the value of t_course.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.name
     *
     * @param name the value for t_course.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.score
     *
     * @return the value of t_course.score
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.score
     *
     * @param score the value for t_course.score
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.create_time
     *
     * @return the value of t_course.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.create_time
     *
     * @param createTime the value for t_course.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.update_time
     *
     * @return the value of t_course.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.update_time
     *
     * @param updateTime the value for t_course.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}