package me.robbie.boot.test.model;

import java.util.Date;

public class TeacherDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.sex
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.birth
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.name
     *
     * @return the value of t_teacher.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.name
     *
     * @param name the value for t_teacher.name
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.sex
     *
     * @return the value of t_teacher.sex
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.sex
     *
     * @param sex the value for t_teacher.sex
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.birth
     *
     * @return the value of t_teacher.birth
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.birth
     *
     * @param birth the value for t_teacher.birth
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.create_time
     *
     * @return the value of t_teacher.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.create_time
     *
     * @param createTime the value for t_teacher.create_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.update_time
     *
     * @return the value of t_teacher.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.update_time
     *
     * @param updateTime the value for t_teacher.update_time
     *
     * @mbggenerated Mon Dec 04 23:14:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}